CREATE SCHEMA IF NOT EXISTS app;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type
    WHERE typname = 'job_status'
    AND typnamespace = 'app'::regnamespace
  ) THEN
    CREATE TYPE app.job_status AS ENUM ('saved','applied','interview','offer','rejected','ghosted');
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS app.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.auth (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES app.users(id) ON DELETE CASCADE,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app.authtoken (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES app.users(id) ON DELETE CASCADE,
  token VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS app.jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES app.users(id) ON DELETE CASCADE,
  date_applied DATE,
  last_date_updated DATE DEFAULT CURRENT_DATE,
  company_name TEXT NOT NULL,
  status app.job_status NOT NULL DEFAULT 'saved',
  position TEXT NOT NULL,
  posting_link TEXT,
  posting_description TEXT,
  resume_text TEXT,
  resume_s3_link TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.authtoken (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES app.users(id) ON DELETE CASCADE,
  token VARCHAR(255) NOT NULL
);


CREATE INDEX IF NOT EXISTS jobs_user_created_idx
  ON app.jobs(user_id, created_at DESC);

CREATE OR REPLACE VIEW app.user_stats AS
SELECT user_id,
       COUNT(*) AS total,
       COUNT(*) FILTER (WHERE status='rejected') AS rejected,
       COUNT(*) FILTER (WHERE status='ghosted') AS ghosted,
       COUNT(*) FILTER (WHERE status='interview') AS interviewing,
       COUNT(*) FILTER (WHERE status='offer') AS offers
FROM app.jobs
GROUP BY user_id;

CREATE OR REPLACE VIEW app.company_stats AS
SELECT user_id, company_name,
       COUNT(*) AS total_applications,
       COUNT(*) FILTER (WHERE status='ghosted') AS number_ghosted,
       MAX(date_applied) AS last_applied_at
FROM app.jobs
GROUP BY user_id, company_name;

CREATE INDEX IF NOT EXISTS jobs_user_status_created_idx ON app.jobs(user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS jobs_user_company_created_idx ON app.jobs(user_id, company_name, created_at DESC);

INSERT INTO app.users(id) VALUES (1) ON CONFLICT (id) DO NOTHING;